#!/bin/sh
# gradle wrapper script
# Generated by Gradle

CLASSPATH=$(dirname "$0")/gradle/wrapper/gradle-wrapper.jar

exec java "$JAVA_OPTS" -classpath "$CLASSPATH" org.gradle.wrapper.GradleWrapperMain "$@"
